"""
Instrument guide chain: SongAnalysis + instrument -> playing tips + chord diagrams.
Vault ref: 03-LangChain-Core/02-Models-Prompts-LCEL.md
"""
from __future__ import annotations

from langchain_core.runnables import Runnable, RunnableLambda, RunnableParallel
from backend.chains.llm_factory import build_llm
from backend.config import get_settings
from backend.prompts.instrument_prompt import instrument_prompt
from backend.schemas import Instrument, InstrumentGuide, SongAnalysis
from backend.tools.voicings import get_chord_diagrams


def _format_inputs(payload: dict) -> dict:
    analysis: SongAnalysis = payload["analysis"]
    return {
        "key": analysis.key,
        "tempo": f"{analysis.tempo:.0f}",
        "chords": " -> ".join(c.chord for c in analysis.chords[:16]),
        "section": payload.get("section", "full song"),
        "instrument": payload["instrument"],
        "difficulty": payload["difficulty"],
    }


from pydantic import BaseModel, Field

class LLMInstrumentTips(BaseModel):
    """Structured playing tips generated by the LLM."""
    strum_pattern: str | None = Field(description="Recommended strumming/picking pattern, e.g. 'D DU UDU'")
    tips: list[str] = Field(description="Practice tips for the student", default_factory=list)
    capo: int | None = Field(description="Suggested capo fret (0 or null if none)", default=None)


def build_instrument_chain() -> Runnable:
    """Runnable expecting: {"analysis": SongAnalysis, "instrument": ..., "difficulty": ...}."""
    s = get_settings()
    llm = build_llm(temperature=s.instrument_temperature)

    # Use structured output for the LLM portion
    structured_llm = llm.with_structured_output(LLMInstrumentTips)
    llm_tips = RunnableLambda(_format_inputs) | instrument_prompt | structured_llm

    def _assemble_guide(results: dict) -> InstrumentGuide:
        payload = results["payload"]
        tips_obj: LLMInstrumentTips = results["tips"]
        diagrams_list = results["diagrams"]

        return InstrumentGuide(
            instrument=payload["instrument"],
            difficulty=payload["difficulty"],
            chord_diagrams=diagrams_list,
            strum_pattern=tips_obj.strum_pattern,
            tips=tips_obj.tips,
            capo=tips_obj.capo,
        )

    # 1. We wrap the inputs so they are passed to the assembler
    # 2. Run LLM tips generation and diagram lookup in parallel
    return RunnableParallel(
        payload=RunnableLambda(lambda x: x),
        tips=llm_tips,
        diagrams=RunnableLambda(
            lambda p: get_chord_diagrams(
                chords=[c.chord for c in p["analysis"].chords],
                instrument=p["instrument"],
            )
        ),
    ) | RunnableLambda(_assemble_guide)
