"""
Instrument guide chain: SongAnalysis + instrument -> playing tips + chord diagrams.
Vault ref: 03-LangChain-Core/02-Models-Prompts-LCEL.md

G3.5: capo is computed once by _deterministic_capo (wrapping suggest_capo) and
injected into the prompt as a fact.  The LLM explains the capo choice; it does
NOT decide it.  LLMInstrumentTips no longer carries a capo field.
"""

from __future__ import annotations

from langchain_core.runnables import Runnable, RunnableLambda, RunnableParallel
from pydantic import BaseModel, Field

from backend.chains.llm_factory import build_structured_llm
from backend.config import get_settings
from backend.prompts.instrument_prompt import instrument_prompt
from backend.schemas import InstrumentGuide, SongAnalysis
from backend.tools.capo import suggest_capo
from backend.tools.transpose import transpose_chord
from backend.tools.voicings import get_chord_diagrams

# ---------------------------------------------------------------------------
# G3.5: single deterministic capo source
# ---------------------------------------------------------------------------

def _deterministic_capo(chords: list[str]) -> int | None:
    """Return the capo fret (1-7) that maximises easy open shapes, or None/0.

    Delegates to suggest_capo (the LangChain @tool) to ensure one code path.
    Returns None when no capo improvement is found (score at fret 0 is best).
    """
    if not chords:
        return None
    result = suggest_capo.invoke({"chords": chords})
    fret = result.get("capo", 0)
    return fret if fret > 0 else None


# ---------------------------------------------------------------------------
# LLM structured output (G3.5: capo field removed)
# ---------------------------------------------------------------------------

class LLMInstrumentTips(BaseModel):
    """Structured playing tips generated by the LLM.

    Note: capo is NOT here — it is computed deterministically by
    _deterministic_capo and passed to the prompt as a fact.
    """

    strum_pattern: str | None = Field(
        description="Recommended strumming/picking pattern, e.g. 'D DU UDU'"
    )
    tips: list[str] = Field(
        description="Practice tips for the student, grounded in the provided capo and chords",
        default_factory=list,
    )


# ---------------------------------------------------------------------------
# Input formatting
# ---------------------------------------------------------------------------

def _format_inputs(payload: dict) -> dict:
    analysis: SongAnalysis = payload["analysis"]
    capo: int | None = payload.get("_capo")
    capo_str = f"capo on fret {capo}" if capo else "no capo"
    return {
        "key": analysis.key,
        "tempo": f"{analysis.tempo:.0f}",
        "chords": " -> ".join(c.chord for c in analysis.chords),
        "section": payload.get("section", "full song"),
        "instrument": payload["instrument"],
        "difficulty": payload["difficulty"],
        "capo": capo_str,
    }


# ---------------------------------------------------------------------------
# Chain builder
# ---------------------------------------------------------------------------

def build_instrument_chain() -> Runnable:
    """Runnable expecting: {"analysis": SongAnalysis, "instrument": ..., "difficulty": ...}."""
    s = get_settings()

    structured_llm = build_structured_llm(
        LLMInstrumentTips, temperature=s.instrument_temperature
    )
    llm_tips = RunnableLambda(_format_inputs) | instrument_prompt | structured_llm

    def _inject_capo(payload: dict) -> dict:
        """Compute capo once and stash it in the payload for downstream steps."""
        if payload["instrument"] in ("guitar", "ukulele"):
            chords = [c.chord for c in payload["analysis"].chords]
            payload = {**payload, "_capo": _deterministic_capo(chords)}
        else:
            payload = {**payload, "_capo": None}
        return payload

    def _assemble_guide(results: dict) -> InstrumentGuide:
        payload = results["payload"]
        tips_obj: LLMInstrumentTips = results["tips"]
        diagrams_list = results["diagrams"]
        capo: int | None = payload.get("_capo")

        return InstrumentGuide(
            instrument=payload["instrument"],
            difficulty=payload["difficulty"],
            chord_diagrams=diagrams_list,
            strum_pattern=tips_obj.strum_pattern,
            tips=tips_obj.tips,
            capo=capo,
        )

    def _get_diagrams(payload: dict) -> list:
        analysis: SongAnalysis = payload["analysis"]
        instrument = payload["instrument"]
        difficulty = payload["difficulty"]
        capo: int | None = payload.get("_capo")

        chord_symbols = [c.chord for c in analysis.chords]
        if capo:
            # Transpose down so the shapes shown are what the player presses
            # with the capo at that fret.
            chord_symbols = [transpose_chord(c, -capo) for c in chord_symbols]

        return get_chord_diagrams(
            chords=chord_symbols,
            instrument=instrument,
            difficulty=difficulty,
        )

    return (
        RunnableLambda(_inject_capo)
        | RunnableParallel(
            payload=RunnableLambda(lambda x: x),
            tips=llm_tips,
            diagrams=RunnableLambda(_get_diagrams),
        )
        | RunnableLambda(_assemble_guide)
    )
