"""
Instrument guide chain: SongAnalysis + instrument -> playing tips + chord diagrams.
Vault ref: 03-LangChain-Core/02-Models-Prompts-LCEL.md
"""

from __future__ import annotations

from langchain_core.runnables import Runnable, RunnableLambda, RunnableParallel

from backend.chains.llm_factory import build_structured_llm
from backend.config import get_settings
from backend.prompts.instrument_prompt import instrument_prompt
from backend.schemas import InstrumentGuide, SongAnalysis
from backend.tools.capo import is_easy_open
from backend.tools.transpose import transpose_chord
from backend.tools.voicings import get_chord_diagrams


def _auto_capo(chords: list[str]) -> int | None:
    """Deterministic capo recommendation (Plan 3 B4).

    Returns the fret 0..7 that turns the most chords into easy open shapes.
    Mirrors :func:`backend.tools.capo.suggest_capo` but without the LangChain
    tool wrapper so we can call it inline from the chain assembler. Returns
    ``None`` when no fret beats the open position.
    """
    if not chords:
        return None
    open_score = sum(is_easy_open(c) for c in chords)
    best_fret = 0
    best_score = open_score
    for fret in range(1, 8):
        shapes = [transpose_chord(c, -fret) for c in chords]
        score = sum(is_easy_open(s) for s in shapes)
        if score > best_score:
            best_score = score
            best_fret = fret
    return best_fret if best_fret > 0 else None


def _format_inputs(payload: dict) -> dict:
    analysis: SongAnalysis = payload["analysis"]
    return {
        "key": analysis.key,
        "tempo": f"{analysis.tempo:.0f}",
        "chords": " -> ".join(c.chord for c in analysis.chords[:16]),
        "section": payload.get("section", "full song"),
        "instrument": payload["instrument"],
        "difficulty": payload["difficulty"],
    }


from pydantic import BaseModel, Field


class LLMInstrumentTips(BaseModel):
    """Structured playing tips generated by the LLM."""

    strum_pattern: str | None = Field(
        description="Recommended strumming/picking pattern, e.g. 'D DU UDU'"
    )
    tips: list[str] = Field(description="Practice tips for the student", default_factory=list)
    capo: int | None = Field(description="Suggested capo fret (0 or null if none)", default=None)


def build_instrument_chain() -> Runnable:
    """Runnable expecting: {"analysis": SongAnalysis, "instrument": ..., "difficulty": ...}."""
    s = get_settings()

    # Structured output applied to each bare provider model before fallback
    # composition (Group 1 P1 fix).
    structured_llm = build_structured_llm(
        LLMInstrumentTips, temperature=s.instrument_temperature
    )
    llm_tips = RunnableLambda(_format_inputs) | instrument_prompt | structured_llm

    def _assemble_guide(results: dict) -> InstrumentGuide:
        payload = results["payload"]
        tips_obj: LLMInstrumentTips = results["tips"]
        diagrams_list = results["diagrams"]

        # Capo precedence (Plan 3 B4):
        #   1. LLM hint if it returned a non-zero suggestion
        #   2. Deterministic auto-capo over the full chord set
        #   3. Otherwise ``None`` (no capo)
        # Only suggest a capo for guitar/ukulele where it's physically meaningful.
        capo = tips_obj.capo
        if (capo is None or capo == 0) and payload["instrument"] in ("guitar", "ukulele"):
            analysis: SongAnalysis = payload["analysis"]
            capo = _auto_capo([c.chord for c in analysis.chords])

        return InstrumentGuide(
            instrument=payload["instrument"],
            difficulty=payload["difficulty"],
            chord_diagrams=diagrams_list,
            strum_pattern=tips_obj.strum_pattern,
            tips=tips_obj.tips,
            capo=capo,
        )

    # 1. We wrap the inputs so they are passed to the assembler
    # 2. Run LLM tips generation and diagram lookup in parallel
    return RunnableParallel(
        payload=RunnableLambda(lambda x: x),
        tips=llm_tips,
        diagrams=RunnableLambda(
            lambda p: get_chord_diagrams(
                chords=[c.chord for c in p["analysis"].chords],
                instrument=p["instrument"],
            )
        ),
    ) | RunnableLambda(_assemble_guide)
