"""
Individual nodes of the analysis graph.
Each node is a pure function: state -> partial state.
Vault ref: 04-LangGraph-Core/02-State-Nodes-Edges.md
"""

from __future__ import annotations

import ipaddress
import logging
import socket
from pathlib import Path
from urllib.parse import urlparse

from backend.graph.state import FEATURE_ERROR_PREFIX, NO_CHORDS_MESSAGE, AnalysisState
from backend.schemas import InstrumentGuide, SongAnalysis


def _song_analysis_from_state(state: AnalysisState) -> SongAnalysis:
    """Pack the analysis-state slice every LLM chain needs.

    Both theory_node and instrument_node feed their LLM chains the same
    SongAnalysis object built from state, so the construction lives here.
    """
    chords = state.get("chords") or []
    return SongAnalysis(
        duration=float(chords[-1].end) if chords else 0.0,
        key=state.get("key", "C major"),
        tempo=state.get("tempo", 120.0),
        chords=chords,
        roman=state.get("roman"),
    )


logger = logging.getLogger(__name__)

# Domains explicitly allowed for yt-dlp ingestion. yt-dlp supports thousands of
# sites; restricting to YouTube prevents the endpoint from being abused as an
# arbitrary URL fetcher.
_YTDLP_ALLOWED_HOSTS = frozenset(
    {
        "youtube.com",
        "www.youtube.com",
        "m.youtube.com",
        "music.youtube.com",
        "youtu.be",
        # Spotify hosts — validated here so the SSRF check still runs
        # even though we go through spotipy (which uses api.spotify.com).
        # The pasted URL itself points at open.spotify.com / embed.spotify.com.
        "open.spotify.com",
        "embed.spotify.com",
    }
)


def _validate_youtube_url(url: str) -> None:
    """Reject non-HTTPS schemes, non-YouTube hosts, and private/loopback IPs (SSRF).

    Raises ValueError with a user-safe message on rejection.
    """
    parsed = urlparse(url)
    if parsed.scheme not in ("http", "https"):
        raise ValueError(f"Unsupported URL scheme: {parsed.scheme!r}")
    host = (parsed.hostname or "").lower()
    if not host:
        raise ValueError("URL has no host")
    if host not in _YTDLP_ALLOWED_HOSTS:
        raise ValueError(f"Host not allowed: {host!r}. Only YouTube URLs are accepted.")
    # Block hosts that resolve to private / loopback / link-local addresses.
    try:
        resolved = socket.getaddrinfo(host, None)
    except socket.gaierror as e:
        raise ValueError(f"Could not resolve host {host!r}: {e}") from e
    for family, _socktype, _proto, _canon, sockaddr in resolved:
        ip_str = sockaddr[0]
        try:
            ip = ipaddress.ip_address(ip_str)
        except ValueError:
            continue
        if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved:
            raise ValueError(f"Host {host!r} resolves to disallowed address range ({ip_str})")


def ingest_node(state: AnalysisState) -> dict:
    """Download YouTube audio or validate uploaded file."""
    youtube_url = state.get("youtube_url")
    audio_path = state.get("audio_path")
    # Collect only NEW errors generated by this node — NOT the accumulated
    # state list. With the operator.add reducer, returning the full prior list
    # would double every prior error. The reducer concatenates this partial
    # with the existing channel value automatically.
    new_errors: list[str] = []
    metadata_extras: dict = {}  # title/artist/etc. from yt-dlp info to merge
    job_id = state.get("job_id", "")

    if youtube_url:
        # Branch by platform. Spotify gets its own flow: metadata-only
        # by default, env-gated YouTube re-download fallback. The
        # ``audio_source`` field tells downstream nodes whether they
        # have real audio to analyze or whether the frontend will play
        # via Spotify's iframe embed.
        from backend.ingestion.url_resolver import classify_url, normalize_to_www_youtube

        platform = classify_url(youtube_url)

        if platform == "spotify":
            from backend.ingestion import spotify as spotify_ingest

            track_id = spotify_ingest.parse_spotify_url(youtube_url)
            if not track_id:
                new_errors.append(
                    f"Rejected URL: could not parse Spotify track ID from {youtube_url!r}"
                )
                return {"audio_path": audio_path, "errors": new_errors}
            spotify_meta = spotify_ingest.fetch_spotify_metadata(track_id) or {}
            metadata_extras.update(spotify_meta)
            # Optional ToS-aware bridge to YouTube (env-gated).
            bridge_url = None
            if spotify_meta.get("title"):
                bridge_url = spotify_ingest.resolve_via_youtube(
                    spotify_meta["title"], spotify_meta.get("artist", "")
                )
            if bridge_url:
                youtube_url = bridge_url  # fall through to the yt-dlp branch
                metadata_extras["audio_source"] = "youtube"
            else:
                # ToS-clean path: no audio download. Frontend renders
                # the Spotify embed iframe instead; analysis pipeline
                # downstream of ingest_node sees missing audio and
                # surfaces a structured "metadata-only" state.
                metadata_extras["audio_source"] = "spotify_embed"
                return {"audio_path": None, "errors": new_errors, **metadata_extras}

        if platform == "youtube_music" or "music.youtube.com" in youtube_url:
            # Normalize music.youtube.com → www.youtube.com so we can use the
            # web_safari/tv clients (which don't need a PO token per session).
            youtube_url = normalize_to_www_youtube(youtube_url)

        try:
            _validate_youtube_url(youtube_url)
        except ValueError as e:
            new_errors.append(f"Rejected URL: {e}")
            return {"audio_path": audio_path, "errors": new_errors}

        try:
            import os
            import shutil

            import yt_dlp

            from backend.config import get_settings

            out_dir = get_settings().audio_upload_dir
            out_dir.mkdir(parents=True, exist_ok=True)

            # In 2026 yt-dlp needs an EJS JS runtime to solve YouTube's
            # signature challenge (per yt-dlp #14515). Prefer Deno (faster
            # solver), fall back to Node. shutil.which uses the parent
            # shell's PATH; deno installed via ``npm i -g deno-bin`` lands
            # under ``$HOME/.npm-global/bin`` which isn't on a Python
            # subprocess's PATH unless the venv is activated — so we also
            # probe the canonical npm-global location explicitly.
            js_runtimes_config: dict[str, dict] = {}
            candidates = [
                ("deno", Path.home() / ".npm-global" / "bin" / "deno"),
                ("deno", Path.home() / ".deno" / "bin" / "deno"),
                ("node", None),
            ]
            for runtime, fallback_path in candidates:
                rt_path = shutil.which(runtime) or (
                    str(fallback_path) if fallback_path and fallback_path.exists() else None
                )
                if rt_path:
                    js_runtimes_config[runtime] = {"path": rt_path}
                    break

            # Locate ffmpeg — prefer system, fall back to the imageio_ffmpeg
            # bundled static binary so the worker keeps running on machines
            # where the operator hasn't ``apt install ffmpeg`` (CI, fresh
            # dev boxes). librosa downstream picks ffmpeg up via the venv
            # PATH so we also symlink at install time (see README).
            ffmpeg_location = shutil.which("ffmpeg")
            if not ffmpeg_location:
                try:
                    import imageio_ffmpeg

                    ffmpeg_location = imageio_ffmpeg.get_ffmpeg_exe()
                except ImportError:
                    pass

            out_path = out_dir / "%(id)s.%(ext)s"
            ydl_opts: dict = {
                "format": "bestaudio/best",
                "outtmpl": str(out_path),
                "postprocessors": [
                    {
                        "key": "FFmpegExtractAudio",
                        "preferredcodec": "mp3",
                        "preferredquality": "192",
                    }
                ],
                "quiet": True,
                # Hardening: never expand playlists, cap file size, fail
                # fast on unexpected redirects to non-YouTube hosts.
                "noplaylist": True,
                "max_filesize": 100 * 1024 * 1024,  # 100 MB
                # 2026 client roster — web_safari + tv bypass SABR throttling
                # better than plain web; android is deprecated for unauth requests.
                "extractor_args": {"youtube": {"player_client": ["web_safari", "tv", "web"]}},
            }
            # Pull the cookie file in from env if set (for age-gated tracks).
            cookie_file = os.environ.get("YTDLP_COOKIES_FILE")
            if cookie_file and Path(cookie_file).exists():
                ydl_opts["cookiefile"] = cookie_file

            # The JS runtime config is passed as a top-level dict key.
            if js_runtimes_config:
                ydl_opts["js_runtimes"] = js_runtimes_config
                # 2026: yt-dlp will only DOWNLOAD the EJS solver script
                # when remote_components allow-list explicitly opts in.
                # Without this, you get "Remote component challenge solver
                # script (node) was skipped" and signature solving fails.
                ydl_opts["remote_components"] = ["ejs:github"]
            if ffmpeg_location:
                ydl_opts["ffmpeg_location"] = ffmpeg_location

            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(youtube_url, download=True)
                # Guard: yt-dlp should always return an info dict with an id,
                # but be explicit so we surface an actionable error rather than
                # an obscure KeyError if the response is malformed.
                video_id = info.get("id") if info else None
                if not video_id:
                    raise ValueError("yt-dlp returned no video id; cannot name the output file")
                # yt-dlp wrote {video_id}.mp3 (outtmpl is %(id)s). Rename it to
                # {job_id}_{video_id}.mp3 so serve_audio / serve_stem / export_midi
                # — all of which key on job_id — can resolve it. Fall back to the
                # raw video-id name if job_id is somehow absent (shouldn't happen
                # in the pipeline, but keep ingest robust when called standalone).
                raw_file = out_dir / f"{video_id}.mp3"
                if job_id:
                    downloaded_file = out_dir / f"{job_id}_{video_id}.mp3"
                    if not raw_file.exists():
                        raise FileNotFoundError(
                            f"yt-dlp produced no output for {video_id!r}; "
                            "the FFmpeg postprocessor may have failed"
                        )
                    raw_file.replace(downloaded_file)
                else:
                    downloaded_file = raw_file
                audio_path = str(downloaded_file)
                # Persist title/uploader as metadata so the player header
                # can show something nicer than the video ID. LangGraph
                # merges the returned dict into state — don't mutate state
                # directly inside a node.
                if info.get("title"):
                    metadata_extras["title"] = info["title"]
                if info.get("uploader"):
                    metadata_extras["artist"] = info["uploader"]
        except Exception as e:
            # Surface yt-dlp's message + an actionable hint instead of just
            # the bare exception (most users won't read "Requested format
            # is not available" and know what to do).
            logger.warning("YouTube download failed for %r: %s", youtube_url, e)
            new_errors.append(
                f"YouTube download failed: {e}. "
                "Try a different URL, or upload the audio file directly."
            )

    # Only fire the "file not found" guard when no earlier error was already
    # recorded (e.g. a yt-dlp exception above).  Without this check a failed
    # YouTube download would append TWO errors: the download failure message
    # AND this "Audio file not found" message, confusing the user.
    if not new_errors and (not audio_path or not Path(audio_path).exists()):
        new_errors.append(f"Audio file not found or failed to load: {audio_path}")
    elif not new_errors and not youtube_url and audio_path and Path(audio_path).exists():
        # Pure file upload with a valid file: try AcoustID fingerprint → MBID
        # enrichment.  Free, graceful no-op if fpcalc or ACOUSTID_API_KEY
        # missing.  Don't run on yt-dlp downloads — we already got
        # title/uploader from the YouTube info dict above.
        from backend.ingestion.acoustid_enrich import enrich_upload

        for k, v in enrich_upload(audio_path).items():
            metadata_extras.setdefault(k, v)

    return {"audio_path": audio_path, "errors": new_errors, **metadata_extras}


def validate_audio_node(state: AnalysisState) -> dict:
    """Validate the staged audio file before ML processing (Plan 2 C3).

    Catches obvious failure modes (missing file, zero bytes, unreadable
    container, oversized duration) and surfaces them as structured errors
    instead of letting the features node crash deep in librosa.
    """
    audio_path = state.get("audio_path")
    # Only return NEW errors (operator.add reducer concatenates; don't re-emit
    # prior state or it doubles). Check prior state separately for the
    # early-exit guard.
    new_errors: list[str] = []

    # If a previous node already errored, don't compound the noise.
    if state.get("errors"):
        return {}

    if not audio_path:
        new_errors.append("validate_audio: no audio path")
        return {"errors": new_errors}

    p = Path(audio_path)
    if not p.exists():
        new_errors.append(f"validate_audio: file does not exist: {audio_path}")
        return {"errors": new_errors}

    try:
        size = p.stat().st_size
    except OSError as e:
        new_errors.append(f"validate_audio: cannot stat {audio_path}: {e}")
        return {"errors": new_errors}

    if size == 0:
        new_errors.append(f"validate_audio: empty file: {audio_path}")
        return {"errors": new_errors}

    # Soft duration check — librosa can probe without fully decoding.
    try:
        import soundfile as sf

        with sf.SoundFile(str(p)) as f:
            duration_s = float(f.frames) / max(f.samplerate, 1)
            sr = f.samplerate
    except Exception as e:
        logger.warning("validate_audio: soundfile probe failed for %s: %s", p, e)
        # Don't hard-fail here — librosa may still load it via the audioread
        # backend. Let features_node be the authoritative loader.
        return {}

    # Hard cap mirrors the ML modules (chord_detection / beat_tracking) which
    # truncate at MAX_AUDIO_DURATION_S already; surfacing it as a clear error
    # is friendlier than silently chopping a 10-minute song to 3 minutes.
    from backend.config import MAX_AUDIO_DURATION_S

    if duration_s > MAX_AUDIO_DURATION_S * 1.05:
        new_errors.append(
            f"validate_audio: duration {duration_s:.1f}s exceeds limit {MAX_AUDIO_DURATION_S}s"
        )
        return {"errors": new_errors}

    if sr < 8000:
        new_errors.append(f"validate_audio: sample rate {sr}Hz is too low for chord analysis")
        return {"errors": new_errors}

    logger.info(
        "validate_audio: %s — duration=%.1fs sr=%d size=%d bytes",
        p.name,
        duration_s,
        sr,
        size,
    )
    return {}


def features_node(state: AnalysisState) -> dict:
    """Extract key, tempo, beats, chords, and song structure (Plan 3 B2).

    Defense-in-depth (live-test report 2): ``retries`` is **always**
    incremented on entry, including on the successful path. This guarantees
    that even if a future bug routes a clean-state run back here (or if the
    conditional edges from ingest/validate get accidentally removed), the
    counter advances and ``should_retry`` will eventually fail rather than
    looping until the 10007-iteration recursion limit fires.

    FT-01: every return path sets ``feature_error`` — ``None`` on success,
    a message on failure. Because ``feature_error`` is a last-write-wins
    channel (no reducer), a successful retry overwrites a prior failure, so
    ``should_retry`` sees the latest attempt's outcome and does NOT treat a
    recovered run as failed. The failure string is *also* appended to the
    append-only ``errors`` log for the audit trail.
    """
    audio_path = state.get("audio_path")
    next_retries = state.get("retries", 0) + 1

    from backend.ml.beat_tracking import track_beats
    from backend.ml.chord_detection import detect_chords
    from backend.ml.key_estimation import (
        disambiguate_relative_key,
        estimate_key_and_tempo,
        refine_tempo,
    )
    from backend.ml.structure_detection import detect_sections

    try:
        estimate = estimate_key_and_tempo(audio_path)
        key, key_confidence = estimate.key, estimate.key_confidence
        beats = track_beats(audio_path)
        beat_times = [b.time for b in beats] if beats else None
        # Phase 4 G4: tempo comes from the SAME beats the UI renders (median
        # interval + octave fold); the librosa onset estimate is the fallback.
        tempo, tempo_confidence = refine_tempo(
            estimate.tempo, estimate.tempo_confidence, beat_times
        )
        # Beat-synchronous chord decoding (Phase 4 G2): chord events snap to
        # beat boundaries when the tracker produced usable beats.
        chords = detect_chords(audio_path, beats=beat_times)
        # Phase 4 G4: relative keys (C major / A minor) share every pitch, so
        # chroma can't separate them — the detected chords' tonic evidence can.
        if chords:
            key = disambiguate_relative_key(key, [c.chord for c in chords])
        sections = detect_sections(audio_path)  # Plan 3 B2; may return []
        # Append an actionable degradation message when chord detection
        # returned nothing (speech, silence, non-harmonic audio).  We do NOT
        # set feature_error here — that would wrongly trigger a retry; chords
        # being empty on a clean extraction is a data-quality issue, not a
        # transient failure.  derive_status will still classify the run as
        # "failed" (no chords == no usable product), but now errors carries a
        # reason the user can act on.
        extra_errors: list[str] = []
        if not chords:
            extra_errors.append(NO_CHORDS_MESSAGE)
        result: dict = {
            "key": key,
            "key_confidence": key_confidence,
            "tempo": tempo,
            "tempo_confidence": tempo_confidence,
            "beats": beats,
            "chords": chords,
            "sections": sections,
            "retries": next_retries,
            "feature_error": None,  # latest attempt succeeded — clear it
        }
        if extra_errors:
            result["errors"] = extra_errors
        return result
    except Exception as e:
        msg = f"{FEATURE_ERROR_PREFIX}: {str(e)}"
        return {
            "errors": [msg],  # append-only log (operator.add reducer)
            "feature_error": msg,  # latest attempt failed
            "retries": next_retries,
        }


def roman_analysis_node(state: AnalysisState) -> dict:
    """Convert chord labels to Roman numerals using music21 (with legacy fallback).

    Delegates to ``backend.theory.roman.analyze_roman`` which:
    - uses music21's ``romanNumeralFromChord`` for correct figured-bass numerals
      (sevenths, inversions, secondary dominants, borrowed chords)
    - detects cadences (PAC/IAC/half/deceptive/plagal) over the numeral sequence
    - detects modulations with a sliding-window key analyzer
    - falls back to the hand-rolled diatonic mapper when music21 is unavailable

    The result is a ``RomanAnalysis`` with:
    - ``entries`` — time-aligned per-chord list (no dedup, no truncation)
    - ``progression`` / ``function`` — legacy fields for TheoryPanel.tsx back-compat
    - ``summary_progression`` — deduped ≤8 numerals for compact UI chips
    - ``cadences`` / ``modulations`` — structured event lists
    """
    key = state.get("key", "C major")
    chords = state.get("chords", [])

    if not chords:
        return {"roman": None}

    from backend.theory.roman import analyze_roman

    try:
        roman = analyze_roman(chords, key)
        return {"roman": roman}
    except Exception as exc:  # pragma: no cover
        # Degradation: log and return None so the fan-out doesn't block
        logging.getLogger(__name__).warning(
            "roman_analysis_node: analyze_roman raised %s; returning None", exc
        )
        return {"roman": None}


def theory_node(state: AnalysisState) -> dict:
    """LLM call: generate structured theory explanation."""
    from backend.chains.theory_chain import build_theory_chain, to_text

    song_obj = _song_analysis_from_state(state)

    try:
        chain = build_theory_chain()
        te = chain.invoke(song_obj)
        # Write both the structured object AND the back-compat string so
        # tasks.py, Mongo persistence, and old consumers all keep working.
        return {
            "theory": te,
            "theory_explanation": to_text(te),
        }
    except Exception as e:
        # Human-friendly degraded message — don't expose raw exception text.
        # The deterministic chord/Roman analysis is still useful on its own;
        # we make that explicit so users don't think analysis is "broken".
        logger.warning("theory_node: LLM unavailable: %s", e)
        key = song_obj.key
        roman = song_obj.roman.progression if song_obj.roman else []
        roman_str = " → ".join(roman[:8]) if roman else "(no progression detected)"
        return {
            "theory": None,
            "errors": ["theory: LLM commentary engine offline; prose explanation skipped"],
            "theory_explanation": (
                f"The deterministic part of the analysis ran cleanly: this song "
                f"is in **{key}** with the progression **{roman_str}**.\n\n"
                f"_The AI commentary engine is offline right now, so the prose "
                f"explanation is unavailable for this run. Restart Ollama (or "
                f"flip ``LLM_PROVIDER`` to a reachable backend) and re-analyze "
                f"to get the full narrative._"
            ),
        }


def instrument_node(state: AnalysisState) -> dict:
    """LLM + deterministic chord-diagram merge -> InstrumentGuide."""
    from backend.chains.instrument_chain import build_instrument_chain

    song_obj = _song_analysis_from_state(state)

    payload = {
        "analysis": song_obj,
        "instrument": state.get("instrument", "guitar"),
        "difficulty": state.get("difficulty", "beginner"),
    }

    try:
        chain = build_instrument_chain()
        guide: InstrumentGuide = chain.invoke(payload)
        return {"instrument_guide": guide}
    except Exception as e:
        # Fall back to a guide containing just the deterministic chord
        # diagrams — better than an empty guide that hides the chord data
        # users came for.
        logger.warning("instrument_node: LLM unavailable: %s", e)
        from backend.tools.voicings import get_chord_diagrams

        chords_list = [c.chord for c in payload["analysis"].chords]
        diagrams = get_chord_diagrams(chords_list, payload["instrument"])
        return {
            "errors": ["instrument: AI tutor offline; chord shapes shown without personalized tips"],
            "instrument_guide": InstrumentGuide(
                instrument=payload["instrument"],
                difficulty=payload["difficulty"],
                chord_diagrams=diagrams,
                tips=[
                    "The AI tutor is offline — chord shapes shown but "
                    "personalized strumming/fingering tips were skipped."
                ],
            ),
        }


def stems_node(state: AnalysisState) -> dict:
    """Stem separation via demucs (Plan 3 A2).

    Gated by ``settings.enable_stems`` so dev boxes without a GPU can
    opt out. The actual demucs call lives in
    :mod:`backend.ml.stem_separation` and uses the ML registry singleton
    so the model loads once per worker process, not per request.

    The returned ``stems`` mapping uses *relative* paths under
    ``settings.stems_dir`` so the persistence layer can store them
    without leaking absolute filesystem paths.
    """
    from backend.config import get_settings
    from backend.ml.stem_separation import separate_stems

    audio_path = state.get("audio_path")
    settings = get_settings()
    if not audio_path or not settings.enable_stems:
        return {}

    # Key the output dir on the job_id carried by state — not on splitting the
    # audio filename, which only happened to work for uploads ({job_id}_{name})
    # and broke for YouTube downloads (named by video_id). Fall back to the old
    # filename-split heuristic only when job_id is absent (standalone calls).
    # NOTE: the filename-split fallback below is unreachable in production
    # (job_id is always present on pipeline state) and kept only for standalone
    # calls (e.g. direct unit-test invocations without a pipeline context).
    job_id = state.get("job_id") or Path(audio_path).stem.split("_")[0]
    out_dir = settings.stems_dir / job_id
    try:
        result = separate_stems(audio_path, out_dir)
    except Exception as e:
        logger.warning("stems_node: separation failed for %s: %s", job_id, e)
        return {"errors": [f"stems: separation failed for job {job_id} ({e})"]}

    # Convert absolute Paths to relative-under-stems_dir strings.
    rel: dict[str, str] = {}
    for stem_name, p in result.items():
        try:
            rel[stem_name] = str(p.relative_to(settings.stems_dir))
        except (ValueError, AttributeError):
            rel[stem_name] = str(p)
    if rel:
        logger.info("stems_node: %d stems for job %s", len(rel), job_id)
    return {"stems": rel}


def has_errors_route(state: AnalysisState) -> str:
    """Conditional-edge helper: route to END as soon as a stage produces errors.

    Used right after :func:`ingest_node` and :func:`validate_audio_node` so a
    bad input (e.g. rejected YouTube URL) terminates the pipeline immediately
    instead of trickling through to ``features_node`` where ``should_retry``
    could loop indefinitely (Plan 3 live-test bug: "Recursion limit of 10007").
    """
    return "fail" if state.get("errors") else "ok"


def should_retry(state: AnalysisState) -> str:
    """Decide whether to retry feature extraction based on the LATEST attempt.

    Reads ``feature_error`` (last-write-wins), NOT the append-only ``errors``
    log. This is the FT-01 fix: a fail-then-succeed sequence leaves a stale
    string in ``errors`` but clears ``feature_error`` to ``None``, so a
    recovered run routes to "ok" instead of being discarded as failed.

    Safety bound: ``features_node`` always increments ``retries`` (success
    or failure), so even pathological inputs can't loop more than a handful
    of times before ``retries >= MAX_FEATURE_RETRIES`` flips us to "fail".
    """
    MAX_FEATURE_RETRIES = 2
    if state.get("feature_error"):
        if state.get("retries", 0) < MAX_FEATURE_RETRIES:
            return "retry"
        return "fail"
    return "ok"
