/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         *
         *     Cheap and always-200 so orchestrators can use this for "is the process
         *     alive" without depending on downstream services. For dependency state,
         *     see :func:`readiness`.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe — pings Mongo and Redis, surfaces per-dependency state.
         *
         *     Returns 200 only when every required dependency is reachable, 503
         *     otherwise with the per-dep breakdown. Use this for Kubernetes
         *     ``readinessProbe`` so traffic doesn't hit a node whose Mongo connection
         *     is wedged.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Kicks off the audio chord and theory analysis pipeline.
         */
        post: operations["analyze_api_v1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyze/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Retrieves the current status or completed result of a song analysis job from MongoDB.
         *
         *     Pass ``?instrument=guitar`` (etc.) to receive the matching instrument guide;
         *     omitting it returns no guide rather than an arbitrary one.
         */
        get: operations["get_analysis_api_v1_analyze__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Progress
         * @description Server-Sent Events stream of analysis progress.
         *
         *     Protocol (Plan 2 D6 — tagged events):
         *         event: chunk    data: {status, progress, message, ...}   (repeated)
         *         event: done     data: {job_id, status: "done", ...}      (terminal)
         *         event: error    data: {code, message}                    (terminal)
         *
         *     Successful jobs end with ``done``; downstream LLM failure or worker
         *     crash ends with ``error``. The frontend ``openProgressStream`` consumer
         *     in :mod:`frontend/web/src/lib/apiClient.ts` handles both new and legacy
         *     formats; once it ships, the backend can stop emitting untagged frames.
         */
        get: operations["get_analysis_progress_api_v1_jobs__job_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Or Update User
         * @description Registers user identity or updates musical preferences in MongoDB.
         */
        post: operations["create_or_update_user_api_v1_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Fetches registered profile metadata from MongoDB.
         */
        get: operations["get_user_profile_api_v1_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Conversational AI assistant. Stores messages and coordinates session caching.
         */
        post: operations["chat_api_v1_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Conversational AI assistant with SSE streaming response.
         */
        post: operations["chat_stream_api_v1_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/history/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description Retrieves standard discussion threads from Cache or drops back to MongoDB.
         */
        get: operations["get_chat_history_api_v1_chat_history__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Kicks off the audio chord and theory analysis pipeline.
         */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Retrieves the current status or completed result of a song analysis job from MongoDB.
         *
         *     Pass ``?instrument=guitar`` (etc.) to receive the matching instrument guide;
         *     omitting it returns no guide rather than an arbitrary one.
         */
        get: operations["get_analysis_analyze__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Progress
         * @description Server-Sent Events stream of analysis progress.
         *
         *     Protocol (Plan 2 D6 — tagged events):
         *         event: chunk    data: {status, progress, message, ...}   (repeated)
         *         event: done     data: {job_id, status: "done", ...}      (terminal)
         *         event: error    data: {code, message}                    (terminal)
         *
         *     Successful jobs end with ``done``; downstream LLM failure or worker
         *     crash ends with ``error``. The frontend ``openProgressStream`` consumer
         *     in :mod:`frontend/web/src/lib/apiClient.ts` handles both new and legacy
         *     formats; once it ships, the backend can stop emitting untagged frames.
         */
        get: operations["get_analysis_progress_jobs__job_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Or Update User
         * @description Registers user identity or updates musical preferences in MongoDB.
         */
        post: operations["create_or_update_user_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile
         * @description Fetches registered profile metadata from MongoDB.
         */
        get: operations["get_user_profile_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Conversational AI assistant. Stores messages and coordinates session caching.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description Conversational AI assistant with SSE streaming response.
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chat History
         * @description Retrieves standard discussion threads from Cache or drops back to MongoDB.
         */
        get: operations["get_chat_history_chat_history__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeResponse */
        AnalyzeResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "done" | "error";
            analysis?: components["schemas"]["SongAnalysis"] | null;
            instrument_guide?: components["schemas"]["InstrumentGuide"] | null;
            /** Error */
            error?: string | null;
        };
        /** BeatEvent */
        BeatEvent: {
            /** Time */
            time: number;
            /**
             * Beat Number
             * @description 1, 2, 3, 4 for 4/4 time
             */
            beat_number: number;
        };
        /** Body_analyze_analyze_post */
        Body_analyze_analyze_post: {
            /** Youtube Url */
            youtube_url?: string | null;
            /**
             * Instrument
             * @default guitar
             */
            instrument: string;
            /**
             * Difficulty
             * @default beginner
             */
            difficulty: string;
            /** User Id */
            user_id?: string | null;
            /** File */
            file?: string | null;
        };
        /** Body_analyze_api_v1_analyze_post */
        Body_analyze_api_v1_analyze_post: {
            /** Youtube Url */
            youtube_url?: string | null;
            /**
             * Instrument
             * @default guitar
             */
            instrument: string;
            /**
             * Difficulty
             * @default beginner
             */
            difficulty: string;
            /** User Id */
            user_id?: string | null;
            /** File */
            file?: string | null;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: {
                [key: string]: unknown;
            }[];
            /** Session Id */
            session_id?: string | null;
            /** User Id */
            user_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
        };
        /**
         * ChordDiagram
         * @description One chord shape for one instrument.
         */
        ChordDiagram: {
            /** Chord */
            chord: string;
            /**
             * Instrument
             * @enum {string}
             */
            instrument: "guitar" | "piano" | "ukulele" | "bass";
            /** Frets */
            frets?: number[] | null;
            /** Fingers */
            fingers?: number[] | null;
            /** Right Hand */
            right_hand?: string[] | null;
            /** Left Hand */
            left_hand?: string[] | null;
        };
        /**
         * ChordEvent
         * @description A single chord at a point in time.
         */
        ChordEvent: {
            /**
             * Start
             * @description Start time in seconds
             */
            start: number;
            /**
             * End
             * @description End time in seconds
             */
            end: number;
            /**
             * Chord
             * @description Chord symbol, e.g. 'Cmaj7', 'Am', 'G/B'
             */
            chord: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Color
             * @description Synesthetic color mapped to this chord
             * @default #8B5CF6
             */
            color: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstrumentGuide */
        InstrumentGuide: {
            /**
             * Instrument
             * @enum {string}
             */
            instrument: "guitar" | "piano" | "ukulele" | "bass";
            /**
             * Difficulty
             * @enum {string}
             */
            difficulty: "beginner" | "intermediate" | "advanced";
            /** Chord Diagrams */
            chord_diagrams: components["schemas"]["ChordDiagram"][];
            /** Strum Pattern */
            strum_pattern?: string | null;
            /** Tips */
            tips?: string[];
            /**
             * Capo
             * @description Capo fret (guitar/uke)
             */
            capo?: number | null;
        };
        /**
         * RomanAnalysis
         * @description Roman-numeral analysis of the progression.
         */
        RomanAnalysis: {
            /** Key */
            key: string;
            /**
             * Progression
             * @description e.g. ['I', 'V', 'vi', 'IV']
             */
            progression: string[];
            /**
             * Function
             * @description e.g. ['tonic', 'dominant', 'submediant', 'subdominant']
             */
            function: string[];
        };
        /**
         * SongAnalysis
         * @description Top-level result returned to the client.
         */
        SongAnalysis: {
            /** Title */
            title?: string | null;
            /** Artist */
            artist?: string | null;
            /** Duration */
            duration: number;
            /**
             * Key
             * @description e.g. 'C major', 'A minor'
             */
            key: string;
            /**
             * Tempo
             * @description BPM
             */
            tempo: number;
            /**
             * Time Signature
             * @default 4/4
             */
            time_signature: string;
            /** Chords */
            chords: components["schemas"]["ChordEvent"][];
            /**
             * Beats
             * @default []
             */
            beats: components["schemas"]["BeatEvent"][];
            /**
             * Sections
             * @default []
             */
            sections: components["schemas"]["SongSection"][];
            roman?: components["schemas"]["RomanAnalysis"] | null;
            /**
             * Vibe Palette
             * @description Synesthetic color palette representing the song's key/vibe
             */
            vibe_palette?: string[];
            /** Theory Explanation */
            theory_explanation?: string | null;
            /** Instrument Guides */
            instrument_guides?: {
                [key: string]: components["schemas"]["InstrumentGuide"];
            };
        };
        /**
         * SongSection
         * @description Intro, verse, chorus, bridge, outro, etc.
         */
        SongSection: {
            /** Name */
            name: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** UserRequest */
        UserRequest: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /**
             * Instrument
             * @default guitar
             */
            instrument: string;
            /**
             * Difficulty
             * @default beginner
             */
            difficulty: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_api_v1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_api_v1_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_analyze__job_id__get: {
        parameters: {
            query?: {
                instrument?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_progress_api_v1_jobs__job_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_or_update_user_api_v1_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_api_v1_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_v1_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_v1_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_api_v1_chat_history__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_analyze_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analyze__job_id__get: {
        parameters: {
            query?: {
                instrument?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_progress_jobs__job_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_or_update_user_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chat_history_chat_history__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
